### PR TITLE
Adding "medieval-text-wikisource" in referece to Pull-Request 839

### PR DESCRIPTION
**Pull request by mayankDhiman**
@Sedictious @kylepjohnson

### CODE REVIEW

**Comment by kylepjohnson** [comment]
Hi thanks for your work with @Sedictious on this.

For our corpus repos, we normally make them per language ([example](https://github.com/cltk/?utf8=%E2%9C%93&q=english&type=&language=)). So if you only want to put English (Old and Middle) texts in here, then call it `english_texts_wikisource`. That name OK with you?

Also @mynkdhmn thanks for adding source and license.

**Comment by kylepjohnson** [comment]
Also @mynkdhmn I would like to see an estimate on how much work it would take to get *all* English texts from Wikisource.

I ask because we could accidentally mislead our users, if they assumed that this repo had everything at Wikisource.

**Comment by mayankDhiman** [comment]
@kylepjohnson Thanks for merging it!
This name is perfectly ok.
This repo contains mostly those texts which use _medieval_ english words. Other than those are not included. Though, all english texts are not there, adding them (_using a scrapper_) won't be a much tough task.

**Comment by tanmaypandey7** [comment]
@kylepjohnson is there anything left to do in here? i ask because https://github.com/cltk/cltk/issues/738 is still marked "open".
Also, I am a little confused because there is a text ["crist_jebson"`](https://github.com/cltk/english_texts_wikisource/blob/master/crist/crist_jebson.txt) and here the text is not complete ( the part after [line 95](https://en.wikisource.org/wiki/The_Exeter_Book_(Jebson)/Christ_A,_B,_C) is missing)

Another doubt i have is regarding a format on how to keep links containing multiple files into a single .txt file ([for example](https://en.wikisource.org/wiki/The_Alexiad)). Here are some of the way i am thinking-
1.  simply create a file the_alexiad.txt and dump everything from the sublinks (like introduction,preface,book 1) in there 
2. in the the_alexiad.txt file write "introduction" then paste/crawl the introduction part, in the next paragraph write "preface" and dump everything from the preface part and so on. But the problem lies here that some links like "book 1" contain another list of contents like chapter 1,chapter 2, chapter 3 etc hence the .txt file can get a little hard to navigate through
3. create multiple folders in "the_alexiad" folder but that may break some tests.


Finally, this has been renamed to "english_texts_wikisource" so will only english texts be included ? If so, there can be some confusion as 
https://github.com/cltk/english_texts_wikisource/blob/master/widsith/widsith.txt is the only one in English.

please let me know if any part is hard to understand and i'll gladly do a better job in explaining.

**Pull request merged**
